accounts/urls.py
from django.urls import path 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

kykf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('enrolments/', include('enrolments.urls', namespace='enrolments')),
    path('kyks/', include('kyks.urls', namespace='kyks')),
    path('supports/', include('supports.urls', namespace='supports')),
    path('workshops/', include('workshops.urls', namespace='workshops')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + debug_toolbar_urls()

#change admin site titles
admin.site.site_header = "KYKF Admin"
admin.site.site_title = "KYKF Admin Portal"
admin.site.index_title = "Welcome to KYKF Admin Portal"

kyks/urls.py
from django.urls import path
from . import views

app_name = 'kyks'

urlpatterns = [
    path('activity', views.activity, name='activity'),
    path('album1', views.album1, name='album1'),
    path('album2', views.album2, name='album2'),   
    path('kyk', views.kyk, name='kyk'),
    path('media', views.media, name='media'),
    path('news', views.news, name='news'),
    ]

pages/urls.py
from django.urls import path 
from . import views 

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

supports/urls.py
from django.urls import path
from . import views

app_name = 'supports'

urlpatterns = [
    path('contact', views.contact, name='contact'),
    path('donation', views.donation, name='donation'),
    path('donation2', views.donation2, name='donation2'),
    path('support', views.support, name='support')    
    
    ]

templates/partials/_alert.html
{% if messages %}
{% for message in messages %}
<div class="container" id="message">
    <div class="alert alert-dismissible text-center alert-{{ message.tags }}" role="alert">
    <button type="button" class="close" data-dismiss="alert"> 
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error: {% else %} 
        {{title}} {% endif %} </strong>{{message}}
    </div>
</div>
{% endfor %}
{% endif %}

templates/partials/_footer.html
<footer style="background-color: #006600;" class="text-white py-4">
        <div class="text-center mt-3">
            <h2>مجھے امید ہے کہ ایک دن آپ ہمارے ساتھ شامل ہوں گے اور دنیا ایک ہو جائے گی۔</h2>
                <p>&copy; 2025 KYK Foundation. All rights reserved.</p>
                <div>
                    <a href="#" style="color: #1877f2; margin-right: 15px;"><i class="fa-brands fa-facebook-f"></i></a>
                    <a href="#" style="color: #ac2bac; margin-right: 15px;"><i class="fab fa-instagram"></i></a>
                    <a href="#" style="color: #14171a; margin-right: 15px;"><i class="fa-brands fa-x-twitter"></i></a>
                </div>
            </div>
        </div>
    </footer>

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #006600;">

    <!-- Toggler button for collapse on small screens -->
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
                </button>

    <!-- Collapsible wrapper for nav items -->
    <div class="collapse navbar-collapse" id="navbarNav">

        <!-- Left nav items -->
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link text-white" href="{% url "supports:contact" %}">Contact Us</a></li>
            <li class="nav-item"><a class="nav-link text-white" href="{% url "supports:support" %}">Support Us</a></li>
            <li class="nav-item"><a class="nav-link text-white" href="{% url "workshops:workshop" %}">Workshops</a></li>
            <li class="nav-item"><a class="nav-link text-white" href="{% url "kyks:kyk" %}">Kung Yung Koon</a></li>
            <li class="nav-item"><a class="nav-link text-white" 
            href="{% url "pages:about" %}">About Us</a></li>
            <li class="nav-item"><a class="nav-link text-white" href="{% url "pages:index" %}">Home</a></li>
            <!-- other left nav items -->
        </ul>

        <!-- Right-aligned navigation items -->
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item mr-3 active">
            <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                <i class="fas fa-user-plus"></i> Welcome {{ user.username }} (dashboard)</a>
            </li>
            <!-- logout -->
            <li class="nav-item mr-3">
                <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                    <i class="fas fa-sign-out-alt"></i>Logout
            </a>
        <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
            {% csrf_token %}
            <input type="hidden"/>
        </form>
        </li>
            {% else %}
            
            <li class="nav-item mr.3 active">
                <a class="nav-link text-white" href="{% url "accounts:login" %}">Login</a></li>
            
            <li class="nav-item mr-3 active">
                <a class="nav-link text-white" href="{% url "accounts:register" %}">Register</a></li>
            {% endif %}
            <img src="{% static 'images/logo3.png' %}" alt="KYK Logo" style="height:40px;">
        </ul>
    </div>
    </nav>