kykf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('enrolments/', include('enrolments.urls', namespace='enrolments')),
    path('kyks/', include('kyks.urls', namespace='kyks')),
    path('supports/', include('supports.urls', namespace='supports')),
    path('workshops/', include('workshops.urls', namespace='workshops')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + debug_toolbar_urls()

#change admin site titles
admin.site.site_header = "KYKF Admin"
admin.site.site_title = "KYKF Admin Portal"
admin.site.index_title = "Welcome to KYKF Admin Portal"

kyks/urls.py
from django.urls import path
from . import views

app_name = 'kyks'

urlpatterns = [
    path('activity', views.activity, name='activity'),
    path('album1', views.album1, name='album1'),
    path('album2', views.album2, name='album2'),   
    path('kyk', views.kyk, name='kyk'),
    path('media', views.media, name='media'),
    path('news', views.news, name='news'),
    ]

pages/urls.py
from django.urls import path 
from . import views 

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

kyks/views.py
from django.shortcuts import render

def activity(request):
    return render(request, 'kyks/activity.html',)

def album1(request):
    return render(request, 'kyks/album1.html',)

def album2(request):
    return render(request, 'kyks/album2.html',)

def kyk(request):
    return render(request, 'kyks/kyk.html',)

def media(request):
    return render(request, 'kyks/media.html',)

def news(request):
    return render(request, 'kyks/news.html',)

# Create your views here.

templates/kyks/activity.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
        <div class="container breadcrumb-container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "kyks:kyk" %}" style="color: #006600"><i class="fa-solid fa-mosque"></i> Kung Yung Koon</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:activity" %}" style="color: #006600"><i class="fas fa-calendar"></i> Activities</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:media" %}" style="color: #006600"><i class="fas fa-video"></i> Media</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:news" %}" style="color: #006600"><i class="fas fa-newspaper"></i> News</a></li>
                </ol>
            </nav>
        </div>
    </section>

<!-- Gallery Section -->
<div class="container">
    <h1 class="gallery-title">Activities launched by KYK</h1>
    <div class="album-container">
        <div class="album-item" onclick="location.href='{% url 'kyks:album1' %}'">
            <div class="album-frame">
                <img src={% static "/images/OP/OP1.jpeg" %} alt="Album 1">
            </div>
            <h3>Ocean Park Day Trip</h3>
        </div>

        <div class="album-item" onclick="location.href='{% url 'kyks:album2' %}'">
            <div class="album-frame">
                <!-- add style="width:170px; height:auto; , when you modify all picture can delete-->
                <img src={% static '/images/HV/HV1.jpeg' %} alt="Album 2" >
            </div>
            <h3>Home Visits</h3>
        </div>
    </div>
</div>


    <!-- Modal for Album 1 -->
    <div id="modalAlbum1" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal('modalAlbum1')">&times;</span>
            <h2>Album 1 Photos</h2>
            <div class="photos">
                <img src={% static "/images/OP/OP1.jpeg" %} alt="OP1">
                <img src={% static "/images/OP/OP2.jpeg" %} alt="OP2">
                <img src={% static "/images/OP/OP3.jpeg" %} alt="OP3">
                <img src={% static "/images/OP/OP4.jpeg" %} alt="OP4">
                <img src={% static "/images/OP/OP5.jpeg" %} alt="OP5">
                <img src={% static "/images/OP/OP6.jpeg" %} alt="OP6">
                <img src={% static "/images/OP/OP7.jpeg" %} alt="OP7">
                <img src={% static "/images/OP/OP8.jpeg" %} alt="OP8">
                <img src={% static "/images/OP/OP9.jpeg" %} alt="OP9">
                <img src={% static "/images/OP/OP10.jpeg" %} alt="OP10">
                <img src={% static "/images/OP/OP11.jpeg" %} alt="OP11">
            </div>
        </div>
    </div>

    <!-- Modal for Album 2 -->
    <!-- Home Visit Modal -->
    <div class="modal fade" id="eventHomeVisitModal" tabindex="-1" aria-labelledby="eventHomeVisitLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="eventHomeVisitLabel">Home Visit & Cantonese Teaching</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>
                        These classes aimed to support Pakistani mothers and students who are in need while it provided a chance for local people to learn more about Pakistani culture.
                    </p>
                    <div class="gallery">
                        <img src="/images/class1.jpeg" alt="Class Photo 1">
                        <img src="/images/class2.jpeg" alt="Class Photo 2">
                        <img src="/images/class3.jpeg" alt="Class Photo 3">
                        <img src="/images/class4.jpeg" alt="Class Photo 4">
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modalAlbum2" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal('modalAlbum2')">&times;</span>
            <h2>Album 2 Photos</h2>
            <div class="photos">
                <img src={% static "/images/OP/HV1.jpeg" %} alt="HV1">
                <img src={% static "/images/OP/HV2.jpeg" %} alt="HV2">
                <img src={% static "/images/OP/HV3.jpeg" %} alt="HV3">
                <img src={% static "/images/OP/HV4.jpeg" %} alt="HV4">
                <img src={% static "/images/OP/HV5.jpeg" %} alt="HV5">
                <img src={% static "/images/OP/HV6.jpeg" %} alt="HV6">
                <img src={% static "/images/OP/HV7.jpeg" %} alt="HV7">
                <img src={% static "/images/OP/HV8.jpeg" %} alt="HV8">
                <img src={% static "/images/OP/HV9.jpeg" %} alt="HV9">
                <img src={% static "/images/OP/HV10.jpeg" %} alt="HV10">
                <img src={% static "/images/OP/HV11.jpeg" %} alt="HV11">
                <img src={% static "/images/OP/HV12.jpeg" %} alt="HV12">
                <img src={% static "/images/OP/HV13.jpeg" %} alt="HV13">
                <img src={% static "/images/OP/HV14.jpeg" %} alt="HV14">
                <img src={% static "/images/OP/HV15.jpeg" %} alt="HV15">
                <img src={% static "/images/OP/HV16.jpeg" %} alt="HV16">
                <img src={% static "/images/OP/HV17.jpeg" %} alt="HV17">
                <img src={% static "/images/OP/HV18.jpeg" %} alt="HV18">
                <img src={% static "/images/OP/HV19.jpeg" %} alt="HV19">
                <img src={% static "/images/OP/HV20.jpeg" %} alt="HV20">
            </div>
        </div>
    </div>

    <!-- Center Button -->
    <div class="center-button">
        <a href="{% url "pages:index" %}" class="btn btn-more-info">Back to Home</a>
    </div>

{% endblock %}

templates/kyks/album1.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
        <div class="container breadcrumb-container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "kyks:kyk" %}" style="color: #006600"><i class="fa-solid fa-mosque"></i> Kung Yung Koon</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:activity" %}" style="color: #006600"><i class="fas fa-calendar"></i> Activities</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:media" %}" style="color: #006600"><i class="fas fa-video"></i> Media</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:news" %}" style="color: #006600"><i class="fas fa-newspaper"></i> News</a></li>
                </ol>
            </nav>
        </div>
    </section>

    <!-- Title Container -->
    <div class="title-container">
        <h1>Ocean Park Day Trip in July 2019</h1>
        <h3>Let's enjoy this joyful moment!</h3>
    </div>

    <!-- Carousel for Activities -->
    <section class="album-section">
        <div class="carousel-container">
            <div class="carousel">
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP2.jpeg" %} alt="OP2">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP3.jpeg" %} alt="OP3">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP4.jpeg" %} alt="OP4">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP5.jpeg" %} alt="OP5">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP6.jpeg" %} alt="OP6">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP7.jpeg" %} alt="OP7">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP8.jpeg" %} alt="OP8">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP9.jpeg" %} alt="OP9">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP10.jpeg" %} alt="OP10">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/OP/OP11.jpeg" %} alt="OP11">
                </div>
            </div>
            <div class="controls">
                <button class="control" id="prev">⟨</button>
                <button class="control" id="next">⟩</button>
            </div>
        </div>
        <!-- Center Button -->
        <div class="center-button">
            <a href="{% url "kyks:activity" %}" class="btn btn-more-info">Back to the album</a>
        </div>
    </section>

{% endblock %}    

templates/kyks/album2.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
        <div class="container breadcrumb-container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "kyks:kyk" %}" style="color: #006600"><i class="fa-solid fa-mosque"></i> Kung Yung Koon</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:activity" %}" style="color: #006600"><i class="fas fa-calendar"></i> Activities</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:media" %}" style="color: #006600"><i class="fas fa-video"></i> Media</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:news" %}" style="color: #006600"><i class="fas fa-newspaper"></i> News</a></li>
                </ol>
            </nav>
        </div>
    </section>

    <!-- Title Container -->
    <div class="title-container">
        <h1>Home Visits to Pakistani Families</h1>
        <h3>Let's enjoy this unforgettable moment!</h3>
    </div>

    <!-- Carousel for Activities -->
    <section class="album-section">
        <div class="carousel-container">
            <div class="carousel">
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV2.jpeg" %} alt="HV2">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV3.jpeg" %} alt="HV3">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV4.jpeg" %} alt="HV4">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV5.jpeg" %} alt="HV5">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV6.jpeg" %} alt="HV6">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV7.jpeg" %} alt="HV7">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV8.jpeg" %} alt="HV8">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV9.jpeg" %} alt="HV9">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV10.jpeg" %} alt="HV10">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV11.jpeg" %} alt="HV11">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV12.jpeg" %} alt="HV12">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV13.jpeg" %} alt="HV13">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV14.jpeg" %} alt="HV14">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV15.jpeg" %} alt="HV15">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV16.jpeg" %} alt="HV16">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV17.jpeg" %} alt="HV17">
                </div>
                <div class="carousel-item">
                    <img src={% static "/images/HV/HV18.jpeg" %} alt="HV18">
                </div>
            </div>
            <div class="controls">
                <button class="control" id="prev">⟨</button>
                <button class="control" id="next">⟩</button>
            </div>
        </div>
        <!-- Center Button -->
        <div class="center-button">
            <a href="{% url "kyks:activity" %}" class="btn btn-more-info"><b>Back to the album</b></a>
        </div>
    </section>

{% endblock %}

templates/kyks/kyk.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<!-- Showcase for KYK -->
    <section id="showcase-inner" class="py-5 showcase-inner">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-5">About Kung Yung Koon</h1>
                    <h2 class="lead"><b>Public Space X Community X Cross-Cultural Engagement</b></h2>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container breadcrumb-container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "kyks:kyk" %}" style="color: #006600"><i class="fa-solid fa-mosque"></i> Kung Yung Koon</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:activity" %}" style="color: #006600"><i class="fas fa-calendar"></i> Activities</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:media" %}" style="color: #006600"><i class="fas fa-video"></i> Media</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:news" %}" style="color: #006600"><i class="fas fa-newspaper"></i> News</a></li>
                    </ol>
            </nav>
        </div>
    </section>
    
    <div id="about" class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8 height: 5000px width: 100%">  
                    <h1>We Empower Communities and Celebrate Diversity in Hong Kong.</h1>
                    <br>
                    <img src={% static "images/KYK1.jpg" %} alt="KYK" class="img-fluid" style="max-height: 1500px;width: 100%; object-fit: cover;"/> 
                    <br/><br>
                    <img src={% static "images/KYK3.jpg" %} alt="KYK" class="img-fluid" style="max-height: 1500px;width: 100%; object-fit: cover;"/>    
                </div>
                <div class="col-md-4">
                    <div class="card" style="min-height: 800px;">
                        <img class="card-img-top img-fluid" src={% static "images/KYK2.jpg" %} alt="KYK2" style="max-height: 600px; width: 100%; object-fit: cover;"/>
                        <div class="card-body" style="height: 725px;">
                            <p class="card-text" style="color: #006600"><b>
                                Kung Yung Koon (KYK) is an non-profit organization for ethnic minorities that nurtures an integrated society where multi-races can adapt and obtain equity.<b>
                                <br><br>
                                <b>We work on empowering the functions of different family roles among South Asians in cooperation with schools, enterprises, organizations, and others.<b>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Center Button -->
    <div class="center-button">
        <a href="{% url "pages:index" %}" class="btn btn-more-info">Back to Home</a>
    </div>

{% endblock %}

templates/kyks/media.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
        <div class="container breadcrumb-container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "kyks:kyk" %}" style="color: #006600"><i class="fa-solid fa-mosque"></i> Kung Yung Koon</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:activity" %}" style="color: #006600"><i class="fas fa-calendar"></i> Activities</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:media" %}" style="color: #006600"><i class="fas fa-video"></i> Media</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:news" %}" style="color: #006600"><i class="fas fa-newspaper"></i> News</a></li>
                </ol>
            </nav>
        </div>
    </section>

<!-- Title Container -->
    <div class="title-container">
        <h1>Get to know more about KYK?</h1>
        <h3>Let's watch its interviews.</h3>
    </div>

    <!-- Carousel for News -->
    <section class="news-section">
        <div class="carousel-container">
            <div class="carousel">
                <div class="carousel-item">
                    <a href="https://www.youtube.com/watch?v=BUFy5P3xir0" target="_blank">
                        <img src="https://img.youtube.com/vi/BUFy5P3xir0/0.jpg"  alt="Video 1 Thumbnail">
                        <div>
                        <i class="fa-brands fa-youtube fa-2xl" style="color: #FF0000;"></i>
                        <span style= color:#006600>About KYK</span>
                        </div>
                    </a>
                    <a href="https://www.youtube.com/watch?v=-KPrZ1OMYT8" target="_blank">
                        <img src="https://img.youtube.com/vi/-KPrZ1OMYT8/0.jpg" alt="Video 2 Thumbnail">
                        <div>
                        <i class="fa-brands fa-youtube fa-2xl" style="color: #FF0000;"></i>
                        <span style= color:#006600><i class="fa-solid fa-mosque"></i> KTK's Mission</span>
                        </div>
                    </a>
                </div>
                <div class="carousel-item">
                    <a href="https://www.youtube.com/watch?v=GeW1CboL_lE" target="_blank">
                        <img src="https://img.youtube.com/vi/GeW1CboL_lE/0.jpg" alt="Video 3 Thumbnail">
                        <div>
                        <i class="fa-brands fa-youtube fa-2xl" style="color: #FF0000;"></i>
                        <span style= color:#006600>Muslims' Lives under Covid-19</span>
                        </div>
                    </a>
                    <a href="https://www.youtube.com/watch?v=v0rOje6hb-c" target="_blank">
                        <img src="https://img.youtube.com/vi/v0rOje6hb-c/0.jpg" alt="Video 4 Thumbnail">
                        <div>
                        <i class="fa-brands fa-youtube fa-2xl" style="color: #FF0000;"></i>
                        <span style= color:#006600>KTK's Local Tours</span>
                        </div>
                    </a>
                </div>
            </div>
            <div class="controls">
                <!-- add text-left and text-right@ 13/01/2026-->
                <button class="control " id="prev">⟨</button>
                <button class="control " id="next">⟩</button>
            </div>
        </div>
        <!-- Center Button -->
        <div class="center-button">
            <a href="{% url "pages:index" %}" class="btn btn-more-info">Back to Home</a>
        </div>
    </section>

{% endblock %}

templates/kyks/news.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
        <div class="container breadcrumb-container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "kyks:kyk" %}" style="color: #006600"><i class="fa-solid fa-mosque"></i> Kung Yung Koon</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:activity" %}" style="color: #006600"><i class="fas fa-calendar"></i> Activities</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:media" %}" style="color: #006600"><i class="fas fa-video"></i> Media</a></li>
                    <li class="breadcrumb-item"><a href="{% url "kyks:news" %}" style="color: #006600"><i class="fas fa-newspaper"></i> News</a></li>
                </ol>
            </nav>
        </div>
    </section>
    
<!-- Timeline Section -->
    <section class="timeline-section container">
        <h2 class="text-center mb-5" style="color: #006600;">News Articles about Kung Yung Koon</h2>
        <div class="timeline">
            <!-- Local Tours Event -->
            <div class="timeline-event timeline-event-left">
                <h3><a href="https://www.hk01.com/18%E5%8D%80%E6%96%B0%E8%81%9E/404376/%E8%91%B5%E6%B6%8C%E6%9C%89%E9%96%93%E6%B8%85%E7%9C%9F%E5%AF%BA-%E5%85%B1%E8%9E%8D%E9%A4%A8%E5%B0%8E%E8%B3%9E%E5%9C%98-%E6%B7%B1%E5%85%A5%E5%B0%8F%E5%B7%B4%E5%9C%BA%E6%96%87%E5%8D%80%E8%A8%AA%E6%B0%91%E9%96%93%E6%B8%85%E7%9C%9F%E5%AF%BA" target="_blank" style="color: white;">Local Tours - Chinese Version</a></h3>
                <p><b>Click to read more news about the tours.</b></p>
            </div>
            <div class="timeline-event timeline-event-right">
                <h3><a href="https://tyr-jour.hkbu.edu.hk/2020/10/27/a-fancy-walk-leads-locals-to-meet-ethnic-minorities-neighbours" target="_blank" style="color: white;">Local Tours - English Version</a></h3>
                <p><b>Click to read more news about the tours.</b></p>
            </div>
            <div class="timeline-event timeline-event-left">
                <h3><a href="https://www.hk01.com/18%E5%8D%80%E6%96%B0%E8%81%9E/403186/%E5%85%B1%E8%9E%8D%E9%A4%A8%E8%BE%A6%E4%BA%8C%E6%89%8B%E6%94%A4%E6%B4%BB%E5%8B%95-%E4%BF%83%E9%80%B2%E5%8D%97%E4%BA%9E%E8%A3%94%E8%88%87%E6%9C%AC%E5%9C%B0%E8%8F%AF%E4%BA%BA%E4%BA%A4%E6%B5%81%E5%85%B1%E8%9E%8D" target="_blank" style="color: white;">Fair for Second-hand Items</a></h3>
                <p><b>Click to read more news about the fair - Chinese Version.</b></p>
            </div>
            <div class="timeline-event timeline-event-right">
                <h3><a href="https://littlepost.hk/2017/02/17/kungyungkoon/" target="_blank" style="color: white;">A visit to Kung Yung Koon</a></h3>
                <p><b>Click to read more news about the visit.</b></p>
            </div>
            <div class="timeline-event timeline-event-left">
                <h3><a href="http://paper.wenweipo.com/2016/12/31/OT1612310001.htm" target="_blank" style="color: white;">Listen to Pakistanis in Hong Kong</a></h3>
                <p><b>Click to read more news about them.</b></p>
            </div>
            <div class="timeline-event timeline-event-right">
                <h3><a href="https://www1.hkej.com/features/article?q=%E8%A8%AA%E8%AB%87%E9%8C%84&suid=3048364184" target="_blank" style="color: white;">Interview on Minhas Rashad 1</a></h3>
                <p><b>Click to read more news about the in-charged person of KYK.</b></p>
            </div>    
            <div class="timeline-event timeline-event-left">
                <h3><a href="https://www.facebook.com/PRAISELMC/posts/dear-friendsthe-newsletter-of-kwai-tsing-story-issue-12-042022-we-are-happy-to-s/166116375783077/" target="_blank" style="color: white;">Interview on Minhas Rashad 2</a></h3>
                <p><b>Click to read more news about the in-charged person of KYK.</b></p>
            </div>    
        </div>
    </section>

    <!-- Modals Section -->
    <!-- Local Tours Modal -->
    <div class="modal fade" id="eventPakistaniTourModal" tabindex="-1" aria-labelledby="eventPakistaniTourLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="eventPakistaniTourLabel">Local Tours: Visiting Pakistani Shops in Kwai Chung</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>To learn more about this tour, visit the news articles: 
                    <a href="https://www.hk01.com/18%E5%8D%80%E6%96%B0%E8%81%9E/404376/%E8%91%B5%E6%B6%8C%E6%9C%89%E9%96%93%E6%B8%85%E7%9C%9F%E5%AF%BA-%E5%85%B1%E8%9E%8D%E9%A4%A8%E5%B0%8E%E8%B3%9E%E5%9C%98-%E6%B7%B1%E5%85%A5%E5%B0%8F%E5%B7%B4%E5%9C%BA%E6%96%87%E5%8D%80%E8%A8%AA%E6%B0%91%E9%96%93%E6%B8%85%E7%9C%9F%E5%AF%BA" target="_blank">Click here to read the full article</a>.
                    <a href="https://www1.hkej.com/features/article?q=%E8%A8%AA%E8%AB%87%E9%8C%84&suid=3048364184" target="_blank">Click here to read the full article</a></p>
                </div>
            </div>
        </div>
    </div>

    
    <!-- Center Button -->
    <div class="center-button">
        <a href="{% url "pages:index" %}" class="btn btn-more-info">Back to Home</a>
    </div>

{% endblock %}